[package]
name = "stargaze"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
bytemuck = { version = "1.25.2", features = ["derive"] }
env_logger = "0.11.11"
font8x8 = "0.3.1"
glam = "0.33.8"
log = "0.4.34"
pollster = "1.0.1"
serde = { version = "1.0", features = ["derive"] }
serde-saphyr = "1.3"
wgpu = "30.0.1"
winit = "0.30.13"

[dev-dependencies]
naga = { version = "30.0.1", features = ["wgsl-in"] }
